[package]
name = "settings"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "1.17.1"
clap = { version = "4.1.11", features = ["derive", "env"] }
bitcoin = "0.30.0"

[lib]
doctest = false
