[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
bitcoin = { version = "0.30.0", features = [ "serde" ] }
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"

[lib]
doctest = false
